#!/bin/bash
# Setup .env file for LlamaStack notebooks
# Automatically detects environment and generates .env file

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_DIR/.env"
ENV_EXAMPLE="$PROJECT_DIR/.env.example"

echo -e "${BLUE}🔧 Setting up .env file for LlamaStack notebooks${NC}"
echo "=========================================="

# Detect if inside OpenShift/Kubernetes cluster
INSIDE_CLUSTER=false
if [ -d "/var/run/secrets/kubernetes.io/serviceaccount" ]; then
    INSIDE_CLUSTER=true
    echo -e "${GREEN}✅ Detected: Running inside OpenShift cluster${NC}"
elif [ -n "$KUBERNETES_SERVICE_HOST" ]; then
    INSIDE_CLUSTER=true
    echo -e "${GREEN}✅ Detected: Running inside Kubernetes cluster${NC}"
else
    echo -e "${YELLOW}📍 Detected: Running outside cluster${NC}"
fi

# Get namespace
if [ "$INSIDE_CLUSTER" = true ]; then
    # Try to read from service account
    if [ -f "/var/run/secrets/kubernetes.io/serviceaccount/namespace" ]; then
        NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
    else
        NAMESPACE="${NAMESPACE:-my-first-model}"
    fi
else
    NAMESPACE="${NAMESPACE:-my-first-model}"
fi

echo "📦 Namespace: $NAMESPACE"

# Function to get route URL
get_route_url() {
    local route_name=$1
    local namespace=$2
    
    if command -v oc &> /dev/null; then
        if oc whoami &> /dev/null; then
            local host=$(oc get route "$route_name" -n "$namespace" -o jsonpath='{.spec.host}' 2>/dev/null)
            if [ -n "$host" ]; then
                echo "https://$host"
                return 0
            fi
        fi
    fi
    return 1
}

# Function to get service URL
get_service_url() {
    local service_name=$1
    local namespace=$2
    local port=${3:-8321}
    
    echo "http://${service_name}.${namespace}.svc.cluster.local:${port}"
}

# Detect LlamaStack URL
LLAMA_STACK_URL=""
if [ -n "$LLAMA_STACK_URL" ]; then
    echo -e "${GREEN}✅ Using LLAMA_STACK_URL from environment${NC}"
elif [ "$INSIDE_CLUSTER" = true ]; then
    # Inside cluster: use service URL
    LLAMA_STACK_URL=$(get_service_url "lsd-llama-milvus-inline-service" "$NAMESPACE" "8321")
    echo -e "${GREEN}✅ Detected LlamaStack service URL${NC}"
else
    # Outside cluster: try to get route
    if route_url=$(get_route_url "llamastack-route" "$NAMESPACE"); then
        LLAMA_STACK_URL="$route_url"
        echo -e "${GREEN}✅ Detected LlamaStack route URL${NC}"
    else
        LLAMA_STACK_URL="http://localhost:8321"
        echo -e "${YELLOW}⚠️  Could not detect LlamaStack route, using localhost${NC}"
        echo "   💡 Set LLAMA_STACK_URL environment variable or update .env manually"
    fi
fi

# Detect MongoDB MCP URL
MCP_MONGODB_URL=""
if [ -n "$MCP_MONGODB_URL" ]; then
    echo -e "${GREEN}✅ Using MCP_MONGODB_URL from environment${NC}"
elif [ "$INSIDE_CLUSTER" = true ]; then
    # Inside cluster: use service URL
    MCP_MONGODB_URL=$(get_service_url "mongodb-mcp-server" "$NAMESPACE" "3000")
    echo -e "${GREEN}✅ Detected MongoDB MCP service URL${NC}"
else
    # Outside cluster: try to get route
    if route_url=$(get_route_url "mongodb-mcp-server-route" "$NAMESPACE"); then
        MCP_MONGODB_URL="$route_url"
        echo -e "${GREEN}✅ Detected MongoDB MCP route URL${NC}"
    else
        MCP_MONGODB_URL="http://localhost:3000"
        echo -e "${YELLOW}⚠️  Could not detect MongoDB MCP route, using localhost${NC}"
        echo "   💡 Set MCP_MONGODB_URL environment variable or update .env manually"
    fi
fi

# Get model (from env or default)
MODEL="${LLAMA_MODEL:-vllm-inference/llama-32-3b-instruct}"

# Generate .env file
echo ""
echo -e "${BLUE}📝 Generating .env file...${NC}"

cat > "$ENV_FILE" << EOF
# LlamaStack Configuration
# Auto-generated by scripts/setup-env.sh
# Environment: $([ "$INSIDE_CLUSTER" = true ] && echo "Inside OpenShift cluster" || echo "Outside OpenShift cluster")
# Generated: $(date)

# LlamaStack URL
# Inside cluster: Service URL
# Outside cluster: Route URL (or localhost if route not found)
LLAMA_STACK_URL=$LLAMA_STACK_URL

# Model identifier
LLAMA_MODEL=$MODEL

# OpenShift namespace
NAMESPACE=$NAMESPACE

# MongoDB MCP Server URL
# Inside cluster: Service URL
# Outside cluster: Route URL (or localhost if route not found)
MCP_MONGODB_URL=$MCP_MONGODB_URL
EOF

echo -e "${GREEN}✅ .env file created: $ENV_FILE${NC}"
echo ""
echo "📋 Configuration:"
echo "   LlamaStack URL: $LLAMA_STACK_URL"
echo "   MongoDB MCP URL: $MCP_MONGODB_URL"
echo "   Model: $MODEL"
echo "   Namespace: $NAMESPACE"
echo ""
echo "💡 To override any value, edit $ENV_FILE or set environment variables"
echo "💡 Example: export LLAMA_STACK_URL='https://custom-url.com' && $0"

